import 'package:flutter/material.dart';
import 'piloto.dart';

List<Piloto> pilotosIniciais = [
  Piloto(
    nome: "Max Verstappen",
    equipe: "Red Bull Racing",
    numero: 1,
    nacionalidade: "Holandês",
    imagem: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677244985/content/dam/fom-website/drivers/M/MAXVER01_Max_Verstappen/maxver01.png",
    corEquipe: Color(0xFF1A1AFF),
    posicao: 1,
    pontos: 180,
    podios: 12,
  ),
  Piloto(
    nome: "Lewis Hamilton",
    equipe: "Mercedes",
    numero: 44,
    nacionalidade: "Britânico",
    imagem: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677244987/content/dam/fom-website/drivers/L/LEWHAM01_Lewis_Hamilton/lewham01.png",
    corEquipe: Color(0xFF00A19C),
    posicao: 2,
    pontos: 150,
    podios: 6,
  ),
  Piloto(
    nome: "Sergio Perez",
    equipe: "Red Bull Racing",
    numero: 11,
    nacionalidade: "Mexicano",
    imagem: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677244986/content/dam/fom-website/drivers/S/SERPER01_Sergio_Perez/serper01.png",
    corEquipe: Color(0xFF1A1AFF),
    posicao: 3,
    pontos: 104,
    podios: 3,
  ),
  Piloto(
    nome: "Lando Norris",
    equipe: "McLaren",
    numero: 4,
    nacionalidade: "Britânico",
    imagem: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677244986/content/dam/fom-website/drivers/L/LANNOR01_Lando_Norris/lannor01.png",
    corEquipe: Color(0xFFB86A00),
    posicao: 4,
    pontos: 90,
    podios: 2,
  ),
  Piloto(
    nome: "Charles Leclerc",
    equipe: "Ferrari",
    numero: 16,
    nacionalidade: "Monegasco",
    imagem: "https://media.formula1.com/image/upload/f_auto/q_auto/v1677244986/content/dam/fom-website/drivers/C/CHALEC01_Charles_Leclerc/chalec01.png",
    corEquipe: Color(0xFF9B0000),
    posicao: 5,
    pontos: 78,
    podios: 1,
  ),
];